# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-22 17:19
from __future__ import unicode_literals

from django.db import migrations, models
import students.validators


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], help_text='Select your gender', max_length=10, validators=[students.validators.validate_gender]),
        ),
    ]
