# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-23 08:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partylists', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partylist',
            name='goals',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partylist',
            name='projects',
            field=models.TextField(blank=True, help_text=b'seperate each item by comma', null=True),
        ),
    ]
